### ISSUE TITLE
amap_map_lite 和 amap_map 1.0.6 两者什么关系

### ISSUE THREAD

**Issue by liuli19920328** [kuloud/amap_map#10]
我应该基于哪个库去开发

**Comment by kuloud** [comment]
> 我应该基于哪个库去开发

基于1.0.6，lite是之前有人提到基于高德轻量版sdk做一层封装，因为空闲时间不多，计划搁置了（后来想了下，其实lite版的需求应该是很弱的，如果有比较重的地图交互，就应该用常规的SDK，要不就用js版，轻量版有点夹生，属于很客制化的场景了）

**Comment by liuli19920328** [comment]
> > 我应该基于哪个库去开发
> 
> 基于1.0.6，lite是之前有人提到基于高德轻量版sdk做一层封装，因为空闲时间不多，计划搁置了（后来想了下，其实lite版的需求应该是很弱的，如果有比较重的地图交互，就应该用常规的SDK，要不就用js版，轻量版有点夹生，属于很客制化的场景了）

谢谢,还有个问题,看箭头指向的文字和指南图标,能调整它们的位置吗?
<img width="518" alt="image" src="https://github.com/kuloud/amap_map/assets/25133477/7f159802-31b1-45e1-943d-b65862669650">

**Comment by kuloud** [comment]
> 谢谢,还有个问题,看箭头指向的文字和指南图标,能调整它们的位置吗?

高德地图logo位置可以改，这周我抽空更新一个版本吧；
指南图标位置改不了，地图SDK内置样式比较丑，一般需要的话都是自己基于水平方向自定义，实在需要可以找一下指南针的组件实现

**Comment by liuli19920328** [comment]
> > 谢谢,还有个问题,看箭头指向的文字和指南图标,能调整它们的位置吗?
> 
> 高德地图logo位置可以改，这周我抽空更新一个版本吧； 指南图标位置改不了，地图SDK内置样式比较丑，一般需要的话都是自己基于水平方向自定义，实在需要可以找一下指南针的组件实现

好的,感谢
