### ISSUE TITLE
缺少搜索功能

### ISSUE THREAD

**Issue by fylw** [kuloud/amap_map#11]
目前缺少搜索功能呢，请问什么时候添加搜索功能

**Comment by kuloud** [comment]
> 目前缺少搜索功能呢，请问什么时候添加搜索功能

这个项目是随缘更新的，近期暂无计划，欢迎 fork 或 pr。
另外地图、导航、搜索是3个独立功能模块，只是高德基础组件设计耦合，才合在一起。搜索直接调用搜索API其实更简单一点，基于SDK封装flutter接口，内部调用的是一样的api，建议自行了解：https://lbs.amap.com/api/webservice/guide/api-advanced/newpoisearch
