### ISSUE TITLE
点击marker如何更新InfoWindowExtension中的widget

### ISSUE THREAD

**Issue by chenhaigang888** [kuloud/amap_map#15]
这个是demo中代码：
final _infoWindowExtension = InfoWindowExtension(
      infoWindow: Container(
        color: Colors.lightBlue.shade400,
        child: Text('info'),
      ),
      option: InfoWindowOption(
          latLng: mapCenter, offset: EdgeInsets.only(bottom: 32)));

**Comment by kuloud** [comment]
> 这个是demo中代码： final _infoWindowExtension = InfoWindowExtension( infoWindow: Container( color: Colors.lightBlue.shade400, child: Text('info'), ), option: InfoWindowOption( latLng: mapCenter, offset: EdgeInsets.only(bottom: 32)));

自行实现 infoWindow 的Widget即可

**Comment by chenhaigang888** [comment]
当我点击其他的marker的时候，infoWindow里的widget的内容无法更新

**Comment by kuloud** [comment]
> 当我点击其他的marker的时候，infoWindow里的widget的内容无法更新

InfoWindow就是一一对应Marker的，你点击其它Marker，就应该显示其它Marker对应的InfoWindow，你可以添加一个_infoWindows的Map，自行管理

**Comment by chenhaigang888** [comment]
我是这么理解的，因为我看那里是一个数组，不过我没有成功
