### ISSUE TITLE
库里面包含amp search的库吗？

### ISSUE THREAD

**Issue by chenhaigang888** [kuloud/amap_map#16]
库里面包含amp search的库吗？
我添加其他searc的库冲突了

**Comment by kuloud** [comment]
> 库里面包含amp search的库吗？ 我添加其他searc的库冲突了

高德SDK 是有search库的，但是search其实直接接一下高德接口就好，sdk也只是做了一个简单的封装，没必要套着sdk单独封装Flutter接口

**Comment by chenhaigang888** [comment]
我用了这2个库，没看到search得API，刚接触flutter 🤣：  
amap_map: ^1.0.8
  #高德定位
 amap_flutter_location: ^3.0.0

**Comment by kuloud** [comment]
> 我用了这2个库，没看到search得API，刚接触flutter 🤣： amap_map: ^1.0.8 #高德定位 amap_flutter_location: ^3.0.0

高德提供的SDK里面集成的search功能仅仅是套了一下他们的搜索POI：https://lbs.amap.com/api/webservice/guide/api-advanced/newpoisearch ，你需要的话，直接http/dio调接口就好，没必要通过组件套SDK，SDK套接口这种形式，舍近求远

**Comment by chenhaigang888** [comment]
好的，谢谢了
