### ISSUE TITLE
求大神更新插件

### ISSUE THREAD

**Issue by JianningRuan** [kuloud/amap_map#4]
求大神更新一个更新插件。现在高德地图android更新到V10.0.6，之前的9.8.3下载不了了

**Comment by kuloud** [comment]
> 求大神更新一个更新插件。现在高德地图android更新到V10.0.6，之前的9.8.3下载不了了

好的 今晚我看看

**Comment by kuloud** [comment]
已处理，android/iOS的高德插件版本已更新到v10.0.600，插件版本1.0.5
