### ISSUE TITLE
demo跑不起来 是有文件没上传吗？

### ISSUE THREAD

**Issue by nnianhouss** [kuloud/amap_map#6]
import 'package:amap_map_example/base_page.dart';找不到

**Comment by kuloud** [comment]
> import 'package:amap_map_example/base_page.dart';找不到

demo 可以跑起来的，工程是从amap_flutter_map fork出来的，重构了example的结构，其中遗漏了几个页面，但缺base_page的页面不会被引用到，不影响编译运行。
