### ISSUE TITLE
想在每公里的地方使用mark来标记公里数，但是目前这个组件好像无法实现？mark不支持文本。 

### ISSUE THREAD

**Issue by knight0zh** [kuloud/amap_map#8]
想在每公里的地方使用mark来标记公里数，但是目前这个组件好像无法实现？mark不支持文本。

**Comment by kuloud** [comment]
> 想在每公里的地方使用mark来标记公里数，但是目前这个组件好像无法实现？mark不支持文本。

对，marker不支持文本的，高德SDK的Marker也是一样的，都是用的BitmapDescriptor，要实现你预期的功能，要么把文本锚点转成BitmapDescriptor，要么如果只是静态展示的话，可以通过坐标转化到屏幕像素，自定义Flutter视图
